import { FullDashboardState } from "./types";

export const initialProjectManhours = {
  DC: 5712,
  GP: 195363,
  TDA: 1152,
  KHOME_174: 69004,
  K_HOME_AVENUE: 0,
  BEN_TRE_HOSPITAL: 124361,
  SYCAMORE_B14: 156210,
  PHU_LONG: 34088,
  BROADWAY: 0,
  SEDO: 23064,
  SWANBAY: 92097,
  STARVIEW: 3008,
};

export const defaultDashboardState: FullDashboardState = {
  header: {
    month: "April",
    year: "2026",
    reporterName: "Nguyen Van An",
    completed: true,
    projectName: "GEM PARK PROJECT (GP)",
  },
  kpis: {
    totalSafeHoursFromStart: 3500210,
    totalSafeHoursYTD: 1412030,
    totalSafeHoursMonth: 320500,
    avgMonthlyWorkers: 450,
    monthlyTrainingHours: 120,
    trainingHoursYTD: 480,
    nearmiss: 12,
    firstAid: 4,
    accidents: 1,
    fatalities: 0,
    reporterName: "Nguyen Van An",
    completed: true,
    avgCloseTimeSVR: 1.2,
  },
  manhourStats: {
    monthlyData: [
      {
        monthIndex: 0, // Jan
        manhoursByProject: {
          DC: 5712,
          GP: 195363,
          TDA: 1152,
          KHOME_174: 69004,
          K_HOME_AVENUE: 0,
          BEN_TRE_HOSPITAL: 124361,
          SYCAMORE_B14: 156210,
          PHU_LONG: 34088,
          BROADWAY: 0,
          SEDO: 23064,
          SWANBAY: 92097,
          STARVIEW: 3008,
        },
        fatalityCount: 0,
        ltiCount: 0,
        daysLost: 0,
        mtcCount: 0,
        firstAidCount: 4,
        nearmissCount: 6,
        svrIssuedCount: 106,
        trainingHoursByProject: { DC: 0, GP: 120, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 1, // Feb
        manhoursByProject: {
          DC: 2400,
          GP: 38216,
          TDA: 160,
          KHOME_174: 18864,
          K_HOME_AVENUE: 0,
          BEN_TRE_HOSPITAL: 41363,
          SYCAMORE_B14: 58660,
          PHU_LONG: 11584,
          BROADWAY: 0,
          SEDO: 16488,
          SWANBAY: 16516,
          STARVIEW: 0,
        },
        fatalityCount: 0,
        ltiCount: 0,
        daysLost: 0,
        mtcCount: 0,
        firstAidCount: 2,
        nearmissCount: 1,
        svrIssuedCount: 85,
        trainingHoursByProject: { DC: 0, GP: 120, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 2, // Mar
        manhoursByProject: {
          DC: 9124,
          GP: 55124,
          TDA: 384,
          KHOME_174: 46688,
          K_HOME_AVENUE: 15656,
          BEN_TRE_HOSPITAL: 96163,
          SYCAMORE_B14: 196930,
          PHU_LONG: 10416,
          BROADWAY: 5344,
          SEDO: 39976,
          SWANBAY: 64538,
          STARVIEW: 0,
        },
        fatalityCount: 0,
        ltiCount: 0,
        daysLost: 0,
        mtcCount: 0,
        firstAidCount: 8,
        nearmissCount: 3,
        svrIssuedCount: 123,
        trainingHoursByProject: { DC: 0, GP: 120, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 3, // Apr
        manhoursByProject: {
          DC: 10496,
          GP: 65961,
          TDA: 0,
          KHOME_174: 41080,
          K_HOME_AVENUE: 35680,
          BEN_TRE_HOSPITAL: 128387,
          SYCAMORE_B14: 226350,
          PHU_LONG: 5656,
          BROADWAY: 32664,
          SEDO: 46744,
          SWANBAY: 59003,
          STARVIEW: 0,
        },
        fatalityCount: 0,
        ltiCount: 0,
        daysLost: 0,
        mtcCount: 0,
        firstAidCount: 7,
        nearmissCount: 3,
        svrIssuedCount: 86,
        trainingHoursByProject: { DC: 0, GP: 120, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      // May to Dec
      {
        monthIndex: 4,
        manhoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
        fatalityCount: 0, ltiCount: 0, daysLost: 0, mtcCount: 0, firstAidCount: 0, nearmissCount: 0, svrIssuedCount: 0,
        trainingHoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 5,
        manhoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
        fatalityCount: 0, ltiCount: 0, daysLost: 0, mtcCount: 0, firstAidCount: 0, nearmissCount: 0, svrIssuedCount: 0,
        trainingHoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 6,
        manhoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
        fatalityCount: 0, ltiCount: 0, daysLost: 0, mtcCount: 0, firstAidCount: 0, nearmissCount: 0, svrIssuedCount: 0,
        trainingHoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 7,
        manhoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
        fatalityCount: 0, ltiCount: 0, daysLost: 0, mtcCount: 0, firstAidCount: 0, nearmissCount: 0, svrIssuedCount: 0,
        trainingHoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 8,
        manhoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
        fatalityCount: 0, ltiCount: 0, daysLost: 0, mtcCount: 0, firstAidCount: 0, nearmissCount: 0, svrIssuedCount: 0,
        trainingHoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 9,
        manhoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
        fatalityCount: 0, ltiCount: 0, daysLost: 0, mtcCount: 0, firstAidCount: 0, nearmissCount: 0, svrIssuedCount: 0,
        trainingHoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 10,
        manhoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
        fatalityCount: 0, ltiCount: 0, daysLost: 0, mtcCount: 0, firstAidCount: 0, nearmissCount: 0, svrIssuedCount: 0,
        trainingHoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      },
      {
        monthIndex: 11,
        manhoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
        fatalityCount: 0, ltiCount: 0, daysLost: 0, mtcCount: 0, firstAidCount: 0, nearmissCount: 0, svrIssuedCount: 0,
        trainingHoursByProject: { DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0, BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0, SEDO: 0, SWANBAY: 0, STARVIEW: 0 },
      }
    ],
    reporterName: "Tran Van Binh",
    completed: true,
  },
  svrAnalysis: {
    categoryCounts: {
      behaviorsPpe: 17,
      lifting: 4,
      excavation: 5,
      workingAtHeight: 17,
      scaffoldStructure: 2,
      housekeeping: 10,
      electrical: 16,
      equipment: 4,
      fireExplosion: 1,
      permitToWork: 2,
      management: 5,
      others: 3,
    },
    projectCounts: {
      DC: 30,
      GP: 11,
      TDA: 0,
      KHOME_174: 81,
      K_HOME_AVENUE: 15,
      BEN_TRE_HOSPITAL: 12,
      SYCAMORE_B14: 30,
      PHU_LONG: 12,
      BROADWAY: 52,
      SEDO: 38,
      SWANBAY: 119,
      STARVIEW: 0,
    },
    reporterName: "Nguyen Van An",
    completed: true,
  },
  safetyPractices: {
    images: [
      {
        id: "img-1",
        title: "PPE Inspection / Kiểm tra trang bị bảo hộ",
        projectName: "GEM PARK (GP)",
        imageUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=600&q=80",
        description: "100% full PPE compliance checked daily at Site Entrance. Công nhân được kiểm tra mũ bảo hộ, đai an toàn và kính bảo vệ trước khi vào công trường.",
        date: "2026-04-10",
        category: "measures"
      },
      {
        id: "img-2",
        title: "Working at Height Fall Protection / An toàn làm việc trên cao",
        projectName: "DIAMOND CITY (DC)",
        imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80",
        description: "Double lanyard safety harness attached safely to static lifeline for fall prevention. Lắp đặt lưới hứng rơi và dây cứu sinh liên tục cho thợ giàn giáo.",
        date: "2026-04-14",
        category: "measures"
      },
      {
        id: "img-3",
        title: "Fire Safety Audit & Hot Work Control / Phòng cháy chữa cháy",
        projectName: "BEN TRE HOSPITAL",
        imageUrl: "https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=600&q=80",
        description: "Weekly extinguishers check and fire station deployment training in hot work zone. Huấn luyện thực hành chữa cháy định kỳ cho đội an toàn cơ sở tháng này.",
        date: "2026-04-20",
        category: "inspection"
      },
      {
        id: "img-4",
        title: "Daily safety toolbox meeting addressing high risks / Họp an toàn đầu giờ",
        projectName: "SYCAMORE B14",
        imageUrl: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=600&q=80",
        description: "15-minute daily briefings addressing risk analysis on deep excavation zone. Chia sẻ rủi ro trước khi vào ca làm việc tại hố móng sâu.",
        date: "2026-04-25",
        category: "training"
      }
    ],
    completed: true
  }
};

export const emptyDashboardState: FullDashboardState = {
  header: {
    month: "January",
    year: "2026",
    reporterName: "",
    completed: false,
    projectName: "",
  },
  kpis: {
    totalSafeHoursFromStart: 0,
    totalSafeHoursYTD: 0,
    totalSafeHoursMonth: 0,
    avgMonthlyWorkers: 0,
    monthlyTrainingHours: 0,
    trainingHoursYTD: 0,
    nearmiss: 0,
    firstAid: 0,
    accidents: 0,
    fatalities: 0,
    reporterName: "",
    completed: false,
    avgCloseTimeSVR: 0.0,
  },
  manhourStats: {
    monthlyData: Array.from({ length: 12 }, (_, index) => ({
      monthIndex: index,
      manhoursByProject: {
        DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0,
        BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0,
        SEDO: 0, SWANBAY: 0, STARVIEW: 0
      },
      fatalityCount: 0,
      ltiCount: 0,
      daysLost: 0,
      mtcCount: 0,
      firstAidCount: 0,
      nearmissCount: 0,
      svrIssuedCount: 0,
      trainingHoursByProject: {
        DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0,
        BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0,
        SEDO: 0, SWANBAY: 0, STARVIEW: 0
      },
    })),
    reporterName: "",
    completed: false,
  },
  svrAnalysis: {
    categoryCounts: {
      behaviorsPpe: 0,
      lifting: 0,
      excavation: 0,
      workingAtHeight: 0,
      scaffoldStructure: 0,
      housekeeping: 0,
      electrical: 0,
      equipment: 0,
      fireExplosion: 0,
      permitToWork: 0,
      management: 0,
      others: 0,
    },
    projectCounts: {
      DC: 0, GP: 0, TDA: 0, KHOME_174: 0, K_HOME_AVENUE: 0,
      BEN_TRE_HOSPITAL: 0, SYCAMORE_B14: 0, PHU_LONG: 0, BROADWAY: 0,
      SEDO: 0, SWANBAY: 0, STARVIEW: 0
    },
    reporterName: "",
    completed: false,
  },
  safetyPractices: {
    images: [],
    completed: false,
  },
};
